# Generated by Django 3.0.4 on 2020-03-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del programa', max_length=150)),
                ('description', models.TextField(help_text='Breve descripcion del programa', max_length=200)),
                ('type', models.CharField(choices=[('Doctorado', 'Doctorado'), ('Maestria', 'Maestria'), ('Diplomado', 'Diplomado')], max_length=20)),
            ],
        ),
    ]
