# Generated by Django 3.0.4 on 2020-03-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='type',
            field=models.CharField(choices=[('phd', 'Doctorado'), ('msc', 'Maestría')], max_length=20),
        ),
    ]
