# Generated by Django 3.0.4 on 2020-03-24 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phdstudent',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='programs.Student'),
        ),
    ]
