# Generated by Django 3.0.4 on 2020-03-24 21:28

from django.db import migrations, models
import django.db.models.deletion
import programs.models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_auto_20200324_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='icon',
            field=models.CharField(choices=[('ion_ios_alarm_outline', 'ion-ios-alarm-outline'), ('ion_ios_albums_outline', 'ion-ios-albums-outline'), ('ion_ios_barcode_outline', 'ion-ios-barcode-outline'), ('ion_ios_body_outline', 'ion-ios-body-outline'), ('ion_ios_book_outline', 'ion-ios-book-outline'), ('ion_ios_calculator_outline', 'ion-ios-calculator-outline'), ('ion_ios_cloudy_outline', 'ion-ios-cloudy-outline'), ('ion_ios_medical_outline', 'ion-ios-medical-outline')], help_text='Seleccione una opcion de la lista', max_length=100),
        ),
        migrations.CreateModel(
            name='ProgramBackgrounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(upload_to=programs.models.background_directory_path)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Program')),
            ],
        ),
    ]
