# Generated by Django 3.0.4 on 2020-03-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_auto_20200320_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='name',
        ),
        migrations.AddField(
            model_name='program',
            name='full_name',
            field=models.CharField(default=1, help_text='Nombre completo del programa', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='short_name',
            field=models.CharField(default=1, help_text='Nombre corto del programa', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='slug',
            field=models.SlugField(default=1, help_text='Slug para url', max_length=40),
            preserve_default=False,
        ),
    ]
