# Generated by Django 3.0.4 on 2020-03-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_auto_20200320_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(help_text='Breve descripcion del programa', max_length=200, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='program',
            name='full_name',
            field=models.CharField(help_text='Nombre completo del programa', max_length=150, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='program',
            name='short_name',
            field=models.CharField(help_text='Nombre corto del programa', max_length=40, verbose_name='Nombre Corto'),
        ),
        migrations.AlterField(
            model_name='program',
            name='type',
            field=models.CharField(choices=[('phd', 'Doctorado'), ('msc', 'Maestría')], max_length=20, verbose_name='Tipo'),
        ),
    ]
