# Generated by Django 3.0.4 on 2020-03-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_auto_20200324_2128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programbackgrounds',
            options={'verbose_name': 'Background', 'verbose_name_plural': 'Backgrounds del index del programa'},
        ),
        migrations.AlterField(
            model_name='programmember',
            name='degree',
            field=models.CharField(help_text='Grado cientifico', max_length=100),
        ),
    ]
