# Generated by Django 3.0.4 on 2020-03-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_auto_20200325_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmember',
            name='role',
            field=models.CharField(choices=[('Coordinador', 'Presidente'), ('Secretario', 'Vicepresidente'), ('Miembro', 'Miembro'), ('Profesor', 'Profesor'), ('Tutor', 'Tutor')], max_length=50),
        ),
    ]
