# Generated by Django 3.0.4 on 2020-03-20 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_auto_20200320_2006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'Programa', 'verbose_name_plural': 'Programas'},
        ),
    ]
