# Generated by Django 3.0.4 on 2020-03-25 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_auto_20200325_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programinitrequirements',
            options={'verbose_name': 'Requerimiento de inicio de programa', 'verbose_name_plural': 'Requerimientos de inicio de programa'},
        ),
        migrations.AlterModelOptions(
            name='programmember',
            options={'verbose_name': 'Miembro del Programa', 'verbose_name_plural': 'Miembros del programa'},
        ),
    ]
