# Generated by Django 3.0.4 on 2020-03-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_auto_20200320_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='slug',
            field=models.SlugField(help_text='Slug para url', max_length=40, unique=True),
        ),
    ]
