# Generated by Django 3.0.4 on 2020-03-20 20:25

from django.db import migrations, models
import programs.models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_auto_20200320_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='address',
            field=models.TextField(default=1, help_text='Dirección de la sede del programa', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='background',
            field=models.ImageField(blank=True, upload_to=programs.models.program_directory_path),
        ),
        migrations.AddField(
            model_name='program',
            name='email',
            field=models.EmailField(default=1, help_text='Email de contacto', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='icon',
            field=models.CharField(choices=[('ion-ios-alarm-outline', 'ion-ios-alarm-outline'), ('ion-ios-albums-outline', 'ion-ios-albums-outline'), ('ion-ios-barcode-outline', 'ion-ios-barcode-outline'), ('ion-ios-body-outline', 'ion-ios-body-outline'), ('ion-ios-book-outline', 'ion-ios-book-outline'), ('ion-ios-calculator-outline', 'ion-ios-calculator-outline'), ('ion-ios-cloudy-outline', 'ion-ios-cloudy-outline'), ('ion-ios-medical-outline', 'ion-ios-medical-outline')], default=1, help_text='Seleccione una opcion de la lista', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='phone',
            field=models.CharField(default=1, help_text='Teléfono de contacto', max_length=20),
            preserve_default=False,
        ),
    ]
