# Generated by Django 3.0.4 on 2020-03-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_auto_20200325_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programfinishrequirements',
            options={'verbose_name': 'Requerimiento de culminacion de programa', 'verbose_name_plural': 'Requerimientos de culminacion de programa'},
        ),
        migrations.AlterField(
            model_name='programmember',
            name='role',
            field=models.CharField(choices=[('Coordinador', 'Coordinador'), ('Secretario', 'Secretario'), ('Miembro', 'Miembro'), ('Profesor', 'Profesor'), ('Tutor', 'Tutor')], max_length=50),
        ),
    ]
