# Generated by Django 3.0.4 on 2020-03-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_auto_20200326_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
