# Generated by Django 3.0.4 on 2020-03-20 20:32

from django.db import migrations, models
import programs.models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_auto_20200320_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='CGC_Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre y apellidos', max_length=120)),
                ('charge', models.CharField(help_text='Cargo', max_length=50)),
                ('priority', models.SmallIntegerField(choices=[('1', 1), ('2', 2), ('3', 3)], help_text='Prioridad del Cargo')),
                ('fb_contact', models.URLField(help_text='URL del contacto de Facebook')),
                ('tw_contact', models.URLField(help_text='URL del contacto de Twitter')),
                ('in_contact', models.URLField(help_text='URL del contacto de Linkedin')),
                ('gp_contact', models.URLField(help_text='URL del contacto de Google+')),
                ('picture', models.ImageField(help_text='Foto', upload_to=programs.models.cgc_photo_directory_path)),
            ],
            options={
                'verbose_name': 'Miembro de la CGC',
                'verbose_name_plural': 'Miembros de la CGC',
            },
        ),
    ]
