# Generated by Django 3.0.4 on 2020-03-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
