# Generated by Django 3.0.4 on 2020-03-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_cgc_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgc_member',
            name='charge',
            field=models.CharField(choices=[('president', 'Presidente'), ('secretary', 'Secretario'), ('member', 'Miembro')], help_text='Cargo', max_length=50),
        ),
    ]
