# Generated by Django 3.0.4 on 2020-03-26 21:12

from django.db import migrations, models
import programs.models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_auto_20200326_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='picture',
            field=models.ImageField(null=True, upload_to=programs.models.student_directory_path),
        ),
    ]
