# Generated by Django 3.0.4 on 2020-03-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_auto_20200320_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgc_member',
            name='priority',
            field=models.SmallIntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3')], help_text='Prioridad del Cargo'),
        ),
    ]
