# Generated by Django 3.0.4 on 2020-03-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0010_student_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programfinishrequirements',
            name='description',
            field=models.CharField(help_text='Descricpion del requisito', max_length=150),
        ),
        migrations.AlterField(
            model_name='programinitrequirements',
            name='description',
            field=models.CharField(help_text='Descripcion del requisito', max_length=150),
        ),
    ]
