# Generated by Django 3.0.4 on 2020-03-20 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import programs.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programs', '0011_auto_20200320_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgc_member',
            name='charge',
            field=models.CharField(choices=[('president', 'Presidente'), ('secretary', 'Secretario'), ('member', 'Miembro')], help_text='Cargo', max_length=50, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='cgc_member',
            name='name',
            field=models.CharField(help_text='Nombre y apellidos', max_length=120, verbose_name='Nombre y apellidos'),
        ),
        migrations.CreateModel(
            name='ProgramMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Coordinador', 'Presidente'), ('Secretario', 'Vicepresidente'), ('Miembro', 'Miembro')], max_length=50)),
                ('institution', models.CharField(max_length=100)),
                ('degree', models.TextField(help_text='Grado cientifico', max_length=300)),
                ('picture', models.ImageField(null=True, upload_to=programs.models.member_directory_path)),
                ('fb_contact', models.CharField(blank=True, help_text='Contacto de Facebook del miembro del tribunal', max_length=50, null=True)),
                ('tw_contact', models.CharField(blank=True, help_text='Contacto de Twitter del miembro del tribunal', max_length=50, null=True)),
                ('ln_contact', models.CharField(blank=True, help_text='Contacto de Linkedin del miembro del tribunal', max_length=50, null=True)),
                ('init_date', models.DateField(default=django.utils.timezone.now)),
                ('sex', models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino')], help_text='Sexo del miembro del tribunal', max_length=2)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Program')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
