# Generated by Django 3.0.4 on 2020-03-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0011_auto_20200327_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='init_date',
            field=models.DateField(null=True),
        ),
    ]
