# Generated by Django 3.0.4 on 2020-03-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0012_student_init_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='F', max_length=1),
        ),
    ]
