# Generated by Django 3.0.4 on 2020-03-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0013_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmember',
            name='phone',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
