# Generated by Django 3.0.4 on 2020-03-21 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0013_phdstudent_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramInitRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del requisito', max_length=50)),
                ('description', models.TextField(help_text='Descricpion del requisito', max_length=150)),
                ('acomplished', models.BooleanField(default=False, help_text='Verdadero si el requisito esta cumplido, Falso si no.')),
                ('program', models.ForeignKey(help_text='Programa correspondiente', on_delete=django.db.models.deletion.CASCADE, to='programs.Program')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramFinishRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del requisito', max_length=50)),
                ('description', models.TextField(help_text='Descricpion del requisito', max_length=150)),
                ('acomplished', models.BooleanField(default=False, help_text='Verdadero si el requisito esta cumplido, Falso si no.')),
                ('program', models.ForeignKey(help_text='Programa correspondiente', on_delete=django.db.models.deletion.CASCADE, to='programs.Program')),
            ],
        ),
    ]
