# Generated by Django 3.0.4 on 2020-03-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0014_programmember_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmember',
            name='country',
            field=models.CharField(default='Cuba', max_length=70),
        ),
    ]
