# Generated by Django 3.0.4 on 2020-03-21 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0014_programfinishrequirements_programinitrequirements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programfinishrequirements',
            name='acomplished',
        ),
        migrations.RemoveField(
            model_name='programinitrequirements',
            name='acomplished',
        ),
        migrations.AlterField(
            model_name='programinitrequirements',
            name='description',
            field=models.TextField(help_text='Descripcion del requisito', max_length=150),
        ),
        migrations.CreateModel(
            name='StudentInitRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accomplished', models.BooleanField(default=False, help_text='Verdadero si esta satisfecho, Falso si lo contrario')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.ProgramInitRequirements')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFinishRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accomplished', models.BooleanField(default=False, help_text='Verdadero si esta satisfecho, Falso si lo contrario')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.ProgramFinishRequirements')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Student')),
            ],
        ),
    ]
