# Generated by Django 3.0.4 on 2020-03-30 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0015_programmember_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigationLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Nombre de la linea', max_length=500)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Program')),
            ],
        ),
        migrations.CreateModel(
            name='PhdStudentTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500, null=True)),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.InvestigationLine')),
                ('phd_student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='programs.PhdStudent')),
            ],
        ),
    ]
