# Generated by Django 3.0.4 on 2020-03-30 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0016_investigationline_phdstudenttheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigationProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=500)),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.InvestigationLine')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.Program')),
            ],
        ),
    ]
