# Generated by Django 3.0.4 on 2020-03-31 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0017_investigationproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='phdstudenttheme',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.InvestigationProject'),
        ),
    ]
