# Generated by Django 3.0.4 on 2020-03-31 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0018_phdstudenttheme_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigationproject',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha de fin del proyecto'),
        ),
        migrations.AddField(
            model_name='investigationproject',
            name='init_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha de inicio del proyecto'),
        ),
        migrations.AddField(
            model_name='investigationproject',
            name='institution',
            field=models.CharField(default=1, help_text='Insitucion coordinadora', max_length=120),
            preserve_default=False,
        ),
    ]
