# Generated by Django 3.0.4 on 2020-04-02 17:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0019_auto_20200331_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 2, 17, 47, 20, 42244, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='student',
            name='dni',
            field=models.CharField(default='12345678901', max_length=11),
        ),
        migrations.AlterField(
            model_name='program',
            name='icon',
            field=models.CharField(choices=[('ion-ios-alarm-outline', 'ion-ios-alarm-outline'), ('ion-ios-albums-outline', 'ion-ios-albums-outline'), ('ion-ios-barcode-outline', 'ion-ios-barcode-outline'), ('ion-ios-body-outline', 'ion-ios-body-outline'), ('ion-ios-book-outline', 'ion-ios-book-outline'), ('ion-ios-calculator-outline', 'ion-ios-calculator-outline'), ('ion-ios-cloudy-outline', 'ion-ios-cloudy-outline'), ('ion-ios-medical-outline', 'ion-ios-medical-outline')], help_text='Seleccione una opcion de la lista', max_length=100),
        ),
    ]
