# Generated by Django 3.0.4 on 2020-04-02 17:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0020_auto_20200402_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 2, 17, 48, 23, 656204, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(default='f', max_length=1),
        ),
    ]
