# Generated by Django 3.0.4 on 2020-04-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0022_auto_20200402_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmember',
            name='weight',
            field=models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, help_text='Peso del Cargo'),
            preserve_default=False,
        ),
    ]
