# Generated by Django 3.0.4 on 2020-04-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0023_programmember_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='cgc_member',
            name='lastname',
            field=models.CharField(default=1, help_text='Apellidos', max_length=70, verbose_name='Apellidos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cgc_member',
            name='name',
            field=models.CharField(help_text='Nombre', max_length=50, verbose_name='Nombre'),
        ),
    ]
