# Generated by Django 3.0.4 on 2020-04-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0024_auto_20200403_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='cgc_member',
            name='gender',
            field=models.CharField(choices=[('f', 'Femenino'), ('m', 'Masculino')], default='m', help_text='Género', max_length=1),
            preserve_default=False,
        ),
    ]
