# Generated by Django 3.0.4 on 2020-04-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0025_cgc_member_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgc_member',
            name='fb_contact',
            field=models.URLField(help_text='URL del contacto de Facebook', null=True),
        ),
        migrations.AlterField(
            model_name='cgc_member',
            name='gp_contact',
            field=models.URLField(help_text='URL del contacto de Google+', null=True),
        ),
        migrations.AlterField(
            model_name='cgc_member',
            name='in_contact',
            field=models.URLField(help_text='URL del contacto de Linkedin', null=True),
        ),
        migrations.AlterField(
            model_name='cgc_member',
            name='tw_contact',
            field=models.URLField(help_text='URL del contacto de Twitter', null=True),
        ),
    ]
