# Generated by Django 3.0.4 on 2020-04-03 19:35

from django.db import migrations, models
import programs.models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0026_auto_20200403_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgc_member',
            name='fb_contact',
            field=models.URLField(blank=True, help_text='URL del contacto de Facebook', null=True),
        ),
        migrations.AlterField(
            model_name='cgc_member',
            name='gp_contact',
            field=models.URLField(blank=True, help_text='URL del contacto de Google+', null=True),
        ),
        migrations.AlterField(
            model_name='cgc_member',
            name='in_contact',
            field=models.URLField(blank=True, help_text='URL del contacto de Linkedin', null=True),
        ),
        migrations.AlterField(
            model_name='cgc_member',
            name='picture',
            field=models.ImageField(blank=True, help_text='Foto', null=True, upload_to=programs.models.cgc_photo_directory_path),
        ),
        migrations.AlterField(
            model_name='cgc_member',
            name='tw_contact',
            field=models.URLField(blank=True, help_text='URL del contacto de Twitter', null=True),
        ),
    ]
