# Generated by Django 3.0.4 on 2020-04-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0027_auto_20200403_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgc_member',
            name='charge',
            field=models.CharField(choices=[('Presidente', 'Presidente'), ('Secretario', 'Secretario'), ('Miembro', 'Miembro')], help_text='Cargo', max_length=50, verbose_name='Cargo'),
        ),
    ]
