# Generated by Django 3.0.4 on 2020-04-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0029_auto_20200403_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgc_member',
            name='fb_contact',
            field=models.URLField(blank=True, default='https://www.facebook.com', help_text='URL del contacto de Facebook'),
        ),
        migrations.AlterField(
            model_name='cgc_member',
            name='gp_contact',
            field=models.URLField(blank=True, default='https://plus.google.com', help_text='URL del contacto de Google+'),
        ),
        migrations.AlterField(
            model_name='cgc_member',
            name='in_contact',
            field=models.URLField(blank=True, default='https://www.linkedin.com', help_text='URL del contacto de Linkedin'),
        ),
        migrations.AlterField(
            model_name='cgc_member',
            name='tw_contact',
            field=models.URLField(blank=True, default='https://www.twitter.com', help_text='URL del contacto de Twitter'),
        ),
    ]
