# Generated by Django 3.0.4 on 2020-04-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0030_auto_20200403_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmember',
            name='birth_date',
            field=models.DateField(default='1960-01-01', help_text='Fecha de nacimiento'),
        ),
    ]
