# Generated by Django 3.0.4 on 2020-04-11 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0032_auto_20200411_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfinishrequirement',
            name='msc_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.MscStudent'),
        ),
    ]
