# Generated by Django 3.0.4 on 2020-04-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0033_studentfinishrequirement_msc_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='type',
            field=models.CharField(choices=[('phd', 'Doctorado'), ('msc', 'Maestría'), ('dip', 'Diplomado')], max_length=20, verbose_name='Tipo'),
        ),
    ]
