# Generated by Django 3.0.4 on 2020-04-11 21:30

from django.db import migrations, models
import programs.models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0035_auto_20200411_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmember',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=programs.models.member_directory_path),
        ),
    ]
