# Generated by Django 3.0.4 on 2020-04-12 16:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0036_auto_20200411_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramEdition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(default=1)),
                ('init_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('observations', models.TextField(max_length=250)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Program')),
            ],
        ),
        migrations.AddField(
            model_name='mscstudent',
            name='edition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programs.ProgramEdition'),
            preserve_default=False,
        ),
    ]
