# Generated by Django 3.0.4 on 2020-04-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0037_auto_20200412_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programedition',
            name='observations',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
