# Generated by Django 3.0.4 on 2020-04-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0039_mscstudenttheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mscstudent',
            name='status',
            field=models.CharField(choices=[('solicitante', 'Solicitante'), ('maestrante', 'Maestrante'), ('graduado', 'Graduado')], default='solicitante', max_length=15),
        ),
    ]
