# Generated by Django 3.0.4 on 2020-04-14 18:56

from django.db import migrations, models
import programs.models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0040_auto_20200414_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mscstudent',
            name='graduate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mscstudent',
            name='init_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mscstudent',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=programs.models.student_directory_path),
        ),
    ]
