# Generated by Django 3.0.4 on 2020-04-15 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0041_auto_20200414_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfinishrequirement',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.Student'),
        ),
    ]
