# Generated by Django 3.0.4 on 2020-04-17 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import programs.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programs', '0042_auto_20200415_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='DipStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('request_date', models.DateField(default=django.utils.timezone.now)),
                ('graduate_date', models.DateField(blank=True, null=True)),
                ('init_date', models.DateField(blank=True, null=True)),
                ('country', models.CharField(default='Cuba', max_length=70)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=programs.models.student_directory_path)),
                ('gender', models.CharField(default='f', max_length=1)),
                ('birth_date', models.DateField(default=django.utils.timezone.now)),
                ('dni', models.CharField(default='12345678901', max_length=11)),
                ('status', models.CharField(choices=[('solicitante', 'Solicitante'), ('diplomante', 'Diplomante'), ('graduado', 'Graduado')], default='solicitante', max_length=15)),
                ('faculty', models.CharField(help_text='Nombre de la Facultad a la que pertenece', max_length=100)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.ProgramEdition')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
