# Generated by Django 3.0.4 on 2020-04-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0044_cgc_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='center',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
