# Generated by Django 3.0.4 on 2020-04-21 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0045_program_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msc_student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.MscStudent')),
                ('phd_student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.PhdStudent')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.ProgramMember')),
            ],
        ),
    ]
