# Generated by Django 3.0.4 on 2020-04-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0046_tuthor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmember',
            name='degree',
            field=models.CharField(default='Doctor en Ciencias de...', help_text='Grado cientifico', max_length=100),
        ),
        migrations.AlterField(
            model_name='programmember',
            name='institution',
            field=models.CharField(default='UNAH', max_length=100),
        ),
        migrations.AlterField(
            model_name='programmember',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='programmember',
            name='sex',
            field=models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino')], default='m', help_text='Sexo del miembro del tribunal', max_length=2),
        ),
        migrations.AlterField(
            model_name='programmember',
            name='weight',
            field=models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, help_text='Peso del Cargo'),
        ),
    ]
