# Generated by Django 3.0.4 on 2020-04-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0047_auto_20200421_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmember',
            name='role',
            field=models.CharField(choices=[('Coordinador', 'Coordinador'), ('Secretario', 'Secretario'), ('Miembro', 'Miembro'), ('Profesor', 'Profesor'), ('Tutor', 'Tutor')], default='Tutor', max_length=50),
        ),
    ]
