# Generated by Django 3.0.4 on 2020-04-24 14:57

from django.db import migrations, models
import programs.models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0048_auto_20200421_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='CGCBrief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief', models.FileField(upload_to=programs.models.cgc_brief_path)),
                ('year', models.IntegerField(default=2020)),
                ('month', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='CNGCBrief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief', models.FileField(upload_to=programs.models.cngc_brief_path)),
                ('year', models.IntegerField(default=2020)),
                ('month', models.IntegerField(default=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='program',
            name='background',
        ),
    ]
