# Generated by Django 3.0.4 on 2020-04-24 15:16

from django.db import migrations, models
import django.db.models.deletion
import programs.models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0049_auto_20200424_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramBrief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief', models.FileField(upload_to=programs.models.program_brief_path)),
                ('year', models.IntegerField(default=2020)),
                ('month', models.IntegerField(default=4)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Program')),
            ],
        ),
    ]
