# Generated by Django 3.0.4 on 2020-04-24 16:59

from django.db import migrations, models
import django.db.models.deletion
import programs.models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0050_programbrief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgcbrief',
            name='brief',
            field=models.FileField(null=True, upload_to=programs.models.cgc_brief_path),
        ),
        migrations.AlterField(
            model_name='cngcbrief',
            name='brief',
            field=models.FileField(null=True, upload_to=programs.models.cngc_brief_path),
        ),
        migrations.AlterField(
            model_name='programbrief',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.Program'),
        ),
    ]
