# Generated by Django 3.0.4 on 2020-04-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0051_auto_20200424_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cgcbrief',
            name='month',
        ),
        migrations.AlterField(
            model_name='cngcbrief',
            name='month',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='programbrief',
            name='month',
            field=models.CharField(max_length=12),
        ),
    ]
