# Generated by Django 3.0.4 on 2020-04-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0052_auto_20200424_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='cgcbrief',
            name='month',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
