# Generated by Django 3.0.4 on 2020-05-04 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0053_cgcbrief_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='cgcbrief',
            name='update_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cngcbrief',
            name='update_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='programbrief',
            name='update_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
