# Generated by Django 3.0.4 on 2020-05-04 20:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0054_auto_20200504_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgcbrief',
            name='update_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 4, 20, 30, 16, 330465, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cngcbrief',
            name='update_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 4, 20, 30, 16, 331068, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='programbrief',
            name='update_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 4, 20, 30, 16, 331662, tzinfo=utc)),
        ),
    ]
