# Generated by Django 3.0.4 on 2020-05-04 20:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0055_auto_20200504_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgcbrief',
            name='update_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cngcbrief',
            name='update_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='programbrief',
            name='update_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
