# Generated by Django 3.0.4 on 2020-05-08 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0056_auto_20200504_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cgc_member',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='cgc_member',
            name='name',
        ),
    ]
