# Generated by Django 3.0.4 on 2020-05-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0057_auto_20200508_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='cgc_member',
            name='institution',
            field=models.CharField(default='Universidad Agraria de La Habana', max_length=60),
        ),
    ]
