# Generated by Django 3.0.4 on 2020-05-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0058_cgc_member_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='cgc_member',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
