# Generated by Django 3.0.4 on 2020-05-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0059_cgc_member_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cgc_member',
            name='degree',
            field=models.CharField(default='Doctor en Ciencias de...', help_text='Grado cientifico', max_length=100),
        ),
    ]
