# Generated by Django 3.0.4 on 2020-05-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0060_cgc_member_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='cgc_member',
            name='birth_date',
            field=models.DateField(default='1960-01-01', help_text='Fecha de nacimiento'),
        ),
    ]
