# Generated by Django 3.0.4 on 2020-05-21 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0061_cgc_member_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=500, null=True)),
                ('init_date', models.DateField(null=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.ProgramEdition')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Program')),
            ],
        ),
    ]
