# Generated by Django 3.0.4 on 2020-05-25 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0062_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='edition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.ProgramEdition'),
        ),
        migrations.CreateModel(
            name='CourseEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Course')),
                ('dipstudent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.DipStudent')),
                ('mscstudent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.MscStudent')),
                ('phdstudent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.PhdStudent')),
            ],
        ),
    ]
