# Generated by Django 3.0.4 on 2020-05-27 17:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0063_auto_20200525_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='init_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
