# Generated by Django 3.0.4 on 2020-06-12 20:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0065_courseprofessor'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFormationPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_end_date', models.DateField()),
                ('elaboration_date', models.DateField(default=django.utils.timezone.now)),
                ('last_update_date', models.DateField(null=True)),
                ('phdstudent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='programs.Student')),
            ],
        ),
        migrations.CreateModel(
            name='FormationPlanActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('description', models.TextField(max_length=500)),
                ('formation_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.StudentFormationPlan')),
            ],
        ),
    ]
