# Generated by Django 3.0.4 on 2020-06-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0066_formationplanactivities_studentformationplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentformationplan',
            name='planned_end_date',
        ),
        migrations.AddField(
            model_name='studentformationplan',
            name='planned_end_year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
