# Generated by Django 3.0.4 on 2020-07-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0067_auto_20200616_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgc_member',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
