# Generated by Django 3.0.4 on 2020-07-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0068_auto_20200701_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgc_member',
            name='degree',
            field=models.CharField(default='Doctor en Ciencias', help_text='Grado cientifico', max_length=100),
        ),
    ]
