# Generated by Django 3.0.4 on 2020-07-09 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0069_auto_20200701_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programmember',
            options={'ordering': ['weight'], 'verbose_name': 'Miembro del Programa', 'verbose_name_plural': 'Miembros del programa'},
        ),
    ]
