# Generated by Django 3.0.4 on 2020-07-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0070_auto_20200709_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='phdstudent',
            name='category',
            field=models.CharField(choices=[('interno', 'Interno'), ('externo', 'Externo')], default='interno', max_length=15),
        ),
        migrations.AddField(
            model_name='phdstudent',
            name='center',
            field=models.CharField(default='Universidad Agraria de La Habana', max_length=150),
        ),
    ]
