# Generated by Django 3.0.4 on 2020-07-15 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0071_auto_20200715_0357'),
    ]

    operations = [
        migrations.CreateModel(
            name='InnerAreas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Areas administrativas para estudiantes internos', max_length=150)),
            ],
        ),
    ]
