# Generated by Django 3.0.4 on 2020-07-15 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0072_innerareas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='innerareas',
            options={'verbose_name': 'Area administrativa interna', 'verbose_name_plural': 'Areas administrativas internas'},
        ),
    ]
