# Generated by Django 3.0.4 on 2020-07-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0073_auto_20200715_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='dipstudent',
            name='category',
            field=models.CharField(choices=[('interno', 'Interno'), ('externo', 'Externo')], default='interno', max_length=15),
        ),
        migrations.AddField(
            model_name='dipstudent',
            name='center',
            field=models.CharField(default='Universidad Agraria de La Habana', max_length=150),
        ),
        migrations.AddField(
            model_name='mscstudent',
            name='category',
            field=models.CharField(choices=[('interno', 'Interno'), ('externo', 'Externo')], default='interno', max_length=15),
        ),
        migrations.AddField(
            model_name='mscstudent',
            name='center',
            field=models.CharField(default='Universidad Agraria de La Habana', max_length=150),
        ),
    ]
