# Generated by Django 3.0.4 on 2020-07-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0075_postgmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='postgmember',
            name='gender',
            field=models.CharField(choices=[('f', 'Femenino'), ('m', 'Masculino')], default='f', max_length=1),
        ),
    ]
