# Generated by Django 3.0.4 on 2020-07-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0076_postgmember_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300, null=True)),
                ('type', models.CharField(choices=[('acta', 'Acta'), ('resolucion', 'Resolución'), ('informe', 'Informe')], default='acta', max_length=20)),
            ],
        ),
    ]
