# Generated by Django 3.0.4 on 2020-08-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0077_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='postgmember',
            name='grade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='postgmember',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='postgmember',
            name='charge',
            field=models.CharField(choices=[('Director', 'Director'), ('Metodólogo', 'Metodólogo'), ('Técnico', 'Técnico')], max_length=20),
        ),
    ]
