# Generated by Django 3.0.4 on 2020-08-04 17:25

from django.db import migrations, models
import programs.models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0078_auto_20200804_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='postgmember',
            name='picture',
            field=models.ImageField(blank=True, help_text='Foto', null=True, upload_to=programs.models.postg_member_directory_path),
        ),
    ]
