# Generated by Django 3.0.4 on 2020-08-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0079_postgmember_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postgmember',
            name='grade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postgmember',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
