# Generated by Django 3.0.4 on 2020-08-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0080_auto_20200805_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='month',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
