# Generated by Django 3.0.4 on 2020-08-06 16:41

from django.db import migrations, models
import programs.models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0081_auto_20200806_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc',
            field=models.FileField(default=1, upload_to=programs.models.postg_document_path),
            preserve_default=False,
        ),
    ]
