# Generated by Django 3.0.10 on 2020-09-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0082_document_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
