# Generated by Django 3.1.1 on 2020-09-02 15:43

from django.db import migrations, models
import django.db.models.deletion
import programs.models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0083_document_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('month', models.CharField(max_length=12)),
                ('description', models.TextField(max_length=300, null=True)),
                ('type', models.CharField(choices=[('acta', 'Acta'), ('resolucion', 'Resolución'), ('informe', 'Informe')], default='acta', max_length=20)),
                ('doc', models.FileField(upload_to=programs.models.program_document_path)),
                ('is_public', models.BooleanField(default=False)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.program')),
            ],
        ),
    ]
