# Generated by Django 3.1.1 on 2020-09-02 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0084_programdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programdocument',
            name='name',
        ),
    ]
