# Generated by Django 3.1.1 on 2020-09-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0085_remove_programdocument_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dipstudent',
            name='dni',
            field=models.CharField(default='12345678901', max_length=24),
        ),
        migrations.AlterField(
            model_name='mscstudent',
            name='dni',
            field=models.CharField(default='12345678901', max_length=24),
        ),
        migrations.AlterField(
            model_name='student',
            name='dni',
            field=models.CharField(default='12345678901', max_length=24),
        ),
    ]
