# Generated by Django 3.1.1 on 2020-09-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0086_auto_20200902_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('acta', 'Acta'), ('resolucion', 'Resolución'), ('informe', 'Informe'), ('otro', 'Otro')], default='acta', max_length=20),
        ),
        migrations.AlterField(
            model_name='programdocument',
            name='type',
            field=models.CharField(choices=[('acta', 'Acta'), ('resolucion', 'Resolución'), ('informe', 'Informe'), ('otro', 'Otro')], default='acta', max_length=20),
        ),
    ]
