# Generated by Django 3.1.1 on 2020-09-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0087_auto_20200902_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_master',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='msc_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
