# Generated by Django 3.1.1 on 2020-09-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0088_auto_20200908_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='have_prorrogue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='prorrogue_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
