# Generated by Django 3.1.1 on 2020-09-09 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0089_auto_20200908_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramFileDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(help_text='Nombre del documento', max_length=100)),
                ('is_init_requirenment', models.BooleanField(default=False, help_text='Marcar si el documento es un requisito de ingreso')),
                ('is_finish_requirenment', models.BooleanField(default=False, help_text='Marcar si el documento es un requisito de egreso')),
                ('just_for_nationals', models.BooleanField(default=False, help_text='Marcar si el documento es un requisito solo para aspirantes nacionales')),
                ('get_old', models.BooleanField(default=False, help_text='Marcar si el documento caduca')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.program')),
            ],
        ),
    ]
