# Generated by Django 3.1.1 on 2020-09-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0090_programfiledoc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programfiledoc',
            options={'verbose_name': 'Documento para el expediente de los estudiantes', 'verbose_name_plural': 'Documentos para el expediente de los estudiantes'},
        ),
        migrations.AlterField(
            model_name='programfiledoc',
            name='doc_name',
            field=models.CharField(help_text='Nombre del documento', max_length=100, verbose_name='Nombre del documento'),
        ),
        migrations.AlterField(
            model_name='programfiledoc',
            name='get_old',
            field=models.BooleanField(default=False, help_text='Marcar si el documento caduca', verbose_name='Caduca'),
        ),
        migrations.AlterField(
            model_name='programfiledoc',
            name='is_finish_requirenment',
            field=models.BooleanField(default=False, help_text='Marcar si el documento es un requisito de egreso', verbose_name='Es Requisito de egreso'),
        ),
        migrations.AlterField(
            model_name='programfiledoc',
            name='is_init_requirenment',
            field=models.BooleanField(default=False, help_text='Marcar si el documento es un requisito de ingreso', verbose_name='Es Requisito de ingreso'),
        ),
        migrations.AlterField(
            model_name='programfiledoc',
            name='just_for_nationals',
            field=models.BooleanField(default=False, help_text='Marcar si el documento es un requisito solo para aspirantes nacionales', verbose_name='Solo para nacionales'),
        ),
    ]
