# Generated by Django 3.1.1 on 2020-09-09 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0091_auto_20200909_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='programfiledoc',
            name='type',
            field=models.CharField(choices=[('student', 'Provisto por el estudiante'), ('program', 'Provisto por el programa')], default='student', help_text='Quien provee el documento', max_length=20, verbose_name='Provisto por'),
        ),
        migrations.CreateModel(
            name='StudentFileDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accomplished', models.BooleanField(default=False, help_text='Verdadero si esta satisfecho, Falso si lo contrario')),
                ('caducity_date', models.DateField(blank=True, null=True)),
                ('dip_student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.dipstudent')),
                ('msc_student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.mscstudent')),
                ('program_file_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.programfiledoc')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.student')),
            ],
        ),
    ]
