# Generated by Django 3.1.1 on 2020-09-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0092_auto_20200909_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programfiledoc',
            name='type',
            field=models.CharField(choices=[('student', 'Estudiante'), ('program', 'Programa'), ('comission', 'Comisión de grados')], default='student', help_text='Quién provee el documento', max_length=20, verbose_name='Provisto por'),
        ),
    ]
