# Generated by Django 3.1.1 on 2020-09-13 14:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0093_auto_20200909_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2020, 9, 13, 14, 56, 21, 695908, tzinfo=utc))),
                ('subject', models.CharField(max_length=250)),
                ('body', models.TextField(max_length=1500)),
                ('readed', models.BooleanField(default=False)),
                ('dip_receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.dipstudent')),
                ('msc_receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.mscstudent')),
                ('phd_receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.student')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.programmember')),
            ],
        ),
    ]
