# Generated by Django 3.1.1 on 2020-09-13 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programs', '0094_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='dip_receiver',
            new_name='dip_student_receiver',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='msc_receiver',
            new_name='msc_student_receiver',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='phd_receiver',
            new_name='phd_student_receiver',
        ),
        migrations.AddField(
            model_name='message',
            name='program_receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.programmember'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
