# Generated by Django 3.1.1 on 2020-09-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0095_auto_20200913_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dipstudent',
            name='status',
            field=models.CharField(choices=[('solicitante', 'Solicitante'), ('diplomante', 'Diplomante'), ('graduado', 'Graduado'), ('denegado', 'Denegado')], default='solicitante', max_length=15),
        ),
        migrations.AlterField(
            model_name='mscstudent',
            name='status',
            field=models.CharField(choices=[('solicitante', 'Solicitante'), ('maestrante', 'Maestrante'), ('graduado', 'Graduado'), ('denegado', 'Denegado')], default='solicitante', max_length=15),
        ),
        migrations.AlterField(
            model_name='phdstudent',
            name='status',
            field=models.CharField(choices=[('solicitante', 'Solicitante'), ('doctorando', 'Doctorando'), ('graduado', 'Graduado'), ('denegado', 'Denegado')], max_length=15),
        ),
    ]
