# Generated by Django 3.1.1 on 2020-09-25 15:30

from django.db import migrations, models
import programs.models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0096_auto_20200916_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='CGCDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('month', models.CharField(max_length=12)),
                ('description', models.TextField(max_length=300, null=True)),
                ('type', models.CharField(choices=[('acta', 'Acta'), ('resolucion', 'Resolución'), ('informe', 'Informe'), ('otro', 'Otro')], default='acta', max_length=20)),
                ('doc', models.FileField(upload_to=programs.models.postg_document_path)),
                ('is_public', models.BooleanField(default=False)),
            ],
        ),
    ]
