# Generated by Django 3.1.1 on 2020-09-25 20:17

from django.db import migrations, models
import programs.models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0097_cgcdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgcdocument',
            name='doc',
            field=models.FileField(upload_to=programs.models.cgc_doc_path),
        ),
    ]
