# Generated by Django 3.1.1 on 2020-09-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0098_auto_20200925_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='cgcdocument',
            name='level',
            field=models.CharField(choices=[('cgc', 'Comisión de Grados Institucional'), ('cngc', 'Comisión Nacional de Grados Científicos')], default='cgc', max_length=5),
        ),
    ]
