# Generated by Django 3.1.2 on 2020-10-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0100_auto_20201006_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Universidad Agraria de la Habana', max_length=150)),
                ('short_name', models.CharField(default='UNAH', max_length=50)),
            ],
        ),
    ]
