# Generated by Django 3.1.2 on 2020-10-17 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0101_institution'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
