# Generated by Django 3.1.2 on 2020-10-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0102_delete_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='formationplanactivities',
            name='observations',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='formationplanactivities',
            name='status',
            field=models.CharField(choices=[['pending', 'Pendiente'], ['ready', 'Cumplida']], default='pending', max_length=10),
        ),
    ]
