# Generated by Django 3.1.2 on 2020-11-17 22:15

from django.db import migrations, models
import django.db.models.deletion
import programs.models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0103_auto_20201027_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=3000)),
                ('img', models.ImageField(blank=True, null=True, upload_to=programs.models.program_new_directory_path)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.program')),
            ],
        ),
    ]
