# Generated by Django 3.1.2 on 2020-11-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0104_new'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'Noticia de programa', 'verbose_name_plural': 'Noticias de programas'},
        ),
        migrations.AlterField(
            model_name='new',
            name='body',
            field=models.TextField(max_length=3000),
        ),
    ]
