# Generated by Django 3.1.2 on 2020-11-17 23:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0105_auto_20201117_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
