# Generated by Django 3.1.2 on 2020-11-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0106_new_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='img',
        ),
        migrations.AlterField(
            model_name='new',
            name='body',
            field=models.TextField(max_length=5000),
        ),
    ]
