# Generated by Django 3.1.2 on 2020-11-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0107_auto_20201119_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(max_length=4000),
        ),
    ]
