# Generated by Django 3.1.2 on 2020-11-21 17:18

from django.db import migrations, models
import programs.models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0108_auto_20201120_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfiledocument',
            name='file',
            field=models.FileField(null=True, upload_to=programs.models.student_filedoc_directory_path),
        ),
    ]
