# Generated by Django 3.1.4 on 2020-12-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0109_studentfiledocument_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='branch',
            field=models.CharField(choices=[('CT', 'Ciencias Técnicas'), ('CE', 'Ciencias Económicas'), ('CNE', 'Ciencias Naturales y Exactas'), ('CA', 'Ciencias Agrícolas'), ('CSH', 'Ciencias Sociales y Humanísticas'), ('CP', 'Ciencias Pedagógicas'), ('Arte', 'Ciencias del Arte')], default='CP', max_length=20, verbose_name='Rama del programa'),
        ),
    ]
