# Generated by Django 3.1.4 on 2020-12-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0110_program_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Codigo del Programa'),
        ),
    ]
