# Generated by Django 3.1.4 on 2021-01-28 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0111_program_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='investigation_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.investigationline'),
        ),
        migrations.AlterField(
            model_name='cgcbrief',
            name='year',
            field=models.IntegerField(default=2021),
        ),
        migrations.AlterField(
            model_name='cngcbrief',
            name='year',
            field=models.IntegerField(default=2021),
        ),
        migrations.AlterField(
            model_name='programbrief',
            name='year',
            field=models.IntegerField(default=2021),
        ),
    ]
