# Generated by Django 3.1.4 on 2021-01-28 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0112_auto_20210128_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='investigation_line',
        ),
    ]
