# Generated by Django 3.1.4 on 2021-01-29 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programs', '0113_remove_student_investigation_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageSended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(choices=[('students', 'Estudiantes'), ('profesores', 'Profesores'), ('comite', 'Comité'), ('personal', 'Personal')], default='personal', max_length=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('subject', models.CharField(max_length=250)),
                ('body', models.TextField(max_length=4000)),
                ('readed', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
