# Generated by Django 3.1.4 on 2021-02-01 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0114_messagesended'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesended',
            name='dip_student_receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.dipstudent'),
        ),
        migrations.AddField(
            model_name='messagesended',
            name='msc_student_receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.mscstudent'),
        ),
        migrations.AddField(
            model_name='messagesended',
            name='phd_student_receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.student'),
        ),
        migrations.AddField(
            model_name='messagesended',
            name='program_receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.programmember'),
        ),
    ]
