# Generated by Django 3.1.4 on 2021-02-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0115_auto_20210201_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='self_request',
            field=models.BooleanField(default=False, help_text='Marcar si se permite la solicitud al programa desde el sitio'),
        ),
    ]
