# Generated by Django 3.1.4 on 2021-04-15 22:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0117_requester'),
    ]

    operations = [
        migrations.AddField(
            model_name='requester',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 15, 22, 44, 30, 512566, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='requester',
            name='request_id',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
