# Generated by Django 3.1.4 on 2021-04-15 22:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0118_auto_20210415_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requester',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 15, 22, 49, 45, 24599, tzinfo=utc)),
        ),
    ]
