# Generated by Django 3.1.4 on 2021-04-16 19:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0119_auto_20210415_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='requester',
            name='planned_end_year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requester',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 16, 19, 39, 34, 285692, tzinfo=utc)),
        ),
    ]
