# Generated by Django 3.2.4 on 2021-06-08 21:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0120_auto_20210416_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requester',
            name='request_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
