# Generated by Django 3.2.7 on 2021-10-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0121_alter_requester_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='requester',
            name='line',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
