# Generated by Django 3.2.11 on 2022-01-13 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0122_requester_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgcbrief',
            name='year',
            field=models.IntegerField(default=2022),
        ),
        migrations.AlterField(
            model_name='cngcbrief',
            name='year',
            field=models.IntegerField(default=2022),
        ),
        migrations.AlterField(
            model_name='programbrief',
            name='year',
            field=models.IntegerField(default=2022),
        ),
    ]
