# Generated by Django 4.1.4 on 2023-01-07 15:58

from django.db import migrations, models
import django.db.models.deletion
import programs.models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0123_auto_20220113_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgcbrief',
            name='year',
            field=models.IntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='cngcbrief',
            name='year',
            field=models.IntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='programbrief',
            name='year',
            field=models.IntegerField(default=2023),
        ),
        migrations.CreateModel(
            name='PhdStudentThesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Título de la tesis', max_length=1500)),
                ('file', models.FileField(help_text='Tesis', upload_to=programs.models.phd_thesis_directory_path)),
                ('phd_student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='programs.phdstudent')),
            ],
        ),
        migrations.CreateModel(
            name='PhdAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='Día y hora de la defensa de tesis')),
                ('text', models.TextField(blank=True, help_text='Texto de la convocatoria', max_length=1500, null=True)),
                ('phd_student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='programs.phdstudent')),
                ('thesis', models.OneToOneField(help_text='Tesis lista para defensa', on_delete=django.db.models.deletion.CASCADE, to='programs.phdstudentthesis')),
            ],
        ),
    ]
