# Generated by Django 4.1.5 on 2023-01-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0124_alter_cgcbrief_year_alter_cngcbrief_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phdannouncement',
            name='place',
            field=models.CharField(default=1, help_text='Lugar en que sesionará la defensa de la tesis', max_length=500, verbose_name='Lugar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phdannouncement',
            name='type',
            field=models.CharField(choices=[('Presencial', 'Presencial'), ('On-line', 'On-line')], default='Presencial', help_text='Modalidad: Presencial u Online', max_length=20, verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='phdannouncement',
            name='date',
            field=models.DateTimeField(help_text='Día y hora del acto de defensa de la tesis', verbose_name='Fecha y hora de la defensa'),
        ),
        migrations.AlterField(
            model_name='phdannouncement',
            name='text',
            field=models.TextField(default=1, help_text='Texto de la convocatoria', max_length=1500, verbose_name='Texto de la convocatoria'),
            preserve_default=False,
        ),
    ]
