# Generated by Django 4.1.5 on 2023-01-13 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0125_phdannouncement_place_phdannouncement_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhdThesisComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('commenter_name', models.CharField(help_text='Nombre y apellidos del que comenta', max_length=100, verbose_name='Nombre y apellidos')),
                ('commenter_email', models.EmailField(help_text='Correo electrónico del que comenta', max_length=100, verbose_name='Correo electrónico')),
                ('text', models.TextField(help_text='Comentario', max_length=2000)),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.phdstudentthesis')),
            ],
        ),
    ]
