# Generated by Django 4.1.5 on 2023-03-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0126_phdthesiscomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phdstudent',
            name='status',
            field=models.CharField(choices=[('solicitante', 'Solicitante'), ('doctorando', 'Doctorando'), ('graduado', 'Graduado'), ('denegado', 'Denegado'), ('baja', 'Baja')], max_length=15),
        ),
    ]
