# Generated by Django 4.2 on 2023-04-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0127_alter_phdstudent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgc_member',
            name='charge',
            field=models.CharField(choices=[('Presidente', 'Presidente'), ('Director', 'Director'), ('Secretario', 'Secretario'), ('Miembro', 'Miembro')], help_text='Cargo', max_length=50, verbose_name='Cargo'),
        ),
    ]
