# Generated by Django 4.2 on 2023-05-10 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0128_alter_cgc_member_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phdannouncement',
            name='text',
        ),
        migrations.AddField(
            model_name='phdannouncement',
            name='approval_resolution',
            field=models.CharField(default=1, help_text='Resolución de la CNGC sobre aprobación del tribunal', max_length=10, verbose_name='Resolución de aprobación del tribunal'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PhdDefenseCourtMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre(s)', max_length=30)),
                ('lastname', models.CharField(help_text='Apellidos', max_length=50)),
                ('center', models.CharField(help_text='Centro de procedencia', max_length=60)),
                ('role', models.CharField(choices=[('Miembro', 'Miembro'), ('Suplente', 'Suplente')], help_text='Rol en el tribunal', max_length=20, verbose_name='Rol en el tribunal')),
                ('thesis', models.ForeignKey(help_text='Tesis lista para defensa', on_delete=django.db.models.deletion.CASCADE, to='programs.phdstudentthesis')),
            ],
        ),
    ]
