# Generated by Django 4.2.1 on 2023-05-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0129_remove_phdannouncement_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phdannouncement',
            name='approval_resolution',
            field=models.CharField(help_text='Número de acuerdo de la CNGC sobre aprobación del tribunal', max_length=10, verbose_name='Acuerdo de aprobación del tribunal'),
        ),
    ]
