# Generated by Django 4.2.1 on 2023-05-11 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0130_alter_phdannouncement_approval_resolution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phdstudentthesis',
            name='title',
        ),
    ]
