# Generated by Django 4.2 on 2023-05-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0131_remove_phdstudentthesis_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='phdannouncement',
            name='sponsor',
            field=models.TextField(blank=True, default='Universidad Agraria de La Habana', help_text='Instituciones que auspician el programa doctoral', max_length=500, null=True, verbose_name='Insituciones auspiciadoras'),
        ),
    ]
