# Generated by Django 4.2 on 2023-05-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0132_phdannouncement_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phdannouncement',
            name='place',
            field=models.CharField(help_text='Lugar en que sesionará la defensa de la tesis', max_length=100, verbose_name='Lugar'),
        ),
        migrations.AlterField(
            model_name='phdannouncement',
            name='sponsor',
            field=models.CharField(blank=True, default='Universidad Agraria de La Habana', help_text='Instituciones que auspician el programa doctoral', max_length=100, null=True, verbose_name='Insituciones auspiciadoras'),
        ),
    ]
