# Generated by Django 4.2.1 on 2023-05-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0133_alter_phdannouncement_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phdannouncement',
            name='url_vc',
            field=models.CharField(blank=True, help_text='URL de la sala virtual de la videoconferencia', max_length=100, null=True, verbose_name='URL de la sala'),
        ),
    ]
