# Generated by Django 4.2.1 on 2024-03-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programs", "0134_phdannouncement_url_vc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cgc_member",
            name="gender",
            field=models.CharField(
                choices=[("m", "Masculino"), ("f", "Femenino")],
                help_text="Género",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="cgcbrief",
            name="year",
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name="cngcbrief",
            name="year",
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name="phdthesiscomment",
            name="text",
            field=models.TextField(
                help_text="Comentario",
                max_length=2000,
                verbose_name="Contenido del comentario",
            ),
        ),
        migrations.AlterField(
            model_name="programbrief",
            name="year",
            field=models.IntegerField(default=2024),
        ),
    ]
