# Generated by Django 4.2.1 on 2025-02-16 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0136_faq_alter_cgcbrief_year_alter_cngcbrief_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.program'),
        ),
    ]
