# Generated by Django 4.2.1 on 2025-02-18 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0137_faq_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
