# Generated by Django 4.2.1 on 2025-04-22 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import programs.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programs', '0138_faq_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColegStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('request_date', models.DateField(default=django.utils.timezone.now)),
                ('graduate_date', models.DateField(blank=True, null=True)),
                ('init_date', models.DateField(blank=True, null=True)),
                ('country', models.CharField(default='Cuba', max_length=70)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=programs.models.student_directory_path)),
                ('gender', models.CharField(default='f', max_length=1)),
                ('birth_date', models.DateField(default=django.utils.timezone.now)),
                ('dni', models.CharField(default='12345678901', max_length=24)),
                ('status', models.CharField(choices=[('solicitante', 'Solicitante'), ('estudiante', 'Estudiante'), ('graduado', 'Graduado'), ('denegado', 'Denegado')], default='solicitante', max_length=15)),
                ('category', models.CharField(choices=[('interno', 'Interno'), ('externo', 'Externo')], default='interno', max_length=15)),
                ('center', models.CharField(default='Universidad de la Habana', max_length=150)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.programedition')),
            ],
        ),
        migrations.CreateModel(
            name='CursStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('request_date', models.DateField(default=django.utils.timezone.now)),
                ('graduate_date', models.DateField(blank=True, null=True)),
                ('init_date', models.DateField(blank=True, null=True)),
                ('country', models.CharField(default='Cuba', max_length=70)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=programs.models.student_directory_path)),
                ('gender', models.CharField(default='f', max_length=1)),
                ('birth_date', models.DateField(default=django.utils.timezone.now)),
                ('dni', models.CharField(default='12345678901', max_length=24)),
                ('status', models.CharField(choices=[('solicitante', 'Solicitante'), ('cursista', 'Cursista'), ('graduado', 'Graduado'), ('denegado', 'Denegado')], default='solicitante', max_length=15)),
                ('category', models.CharField(choices=[('interno', 'Interno'), ('externo', 'Externo')], default='interno', max_length=15)),
                ('center', models.CharField(default='Universidad de la Habana', max_length=150)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.programedition')),
            ],
        ),
        migrations.AlterField(
            model_name='cgc_member',
            name='institution',
            field=models.CharField(default='Universidad de la Habana', max_length=60),
        ),
        migrations.AlterField(
            model_name='dipstudent',
            name='center',
            field=models.CharField(default='Universidad de la Habana', max_length=150),
        ),
        migrations.AlterField(
            model_name='mscstudent',
            name='center',
            field=models.CharField(default='Universidad de la Habana', max_length=150),
        ),
        migrations.AlterField(
            model_name='mscstudenttheme',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.mscstudent'),
        ),
        migrations.AlterField(
            model_name='phdannouncement',
            name='sponsor',
            field=models.CharField(blank=True, default='Universidad de la Habana', help_text='Instituciones que auspician el programa doctoral', max_length=100, null=True, verbose_name='Insituciones auspiciadoras'),
        ),
        migrations.AlterField(
            model_name='phdstudent',
            name='center',
            field=models.CharField(default='Universidad de la Habana', max_length=150),
        ),
        migrations.AlterField(
            model_name='program',
            name='branch',
            field=models.CharField(choices=[('CT', 'Ciencias Técnicas'), ('CE', 'Ciencias Económicas'), ('CNE', 'Ciencias Naturales y Exactas'), ('CA', 'Ciencias Agrícolas'), ('CSH', 'Ciencias Sociales y Humanísticas'), ('CP', 'Ciencias Pedagógicas'), ('Arte', 'Ciencias del Arte'), ('Otros', 'Otros')], default='CP', max_length=20, verbose_name='Rama del programa'),
        ),
        migrations.AlterField(
            model_name='program',
            name='type',
            field=models.CharField(choices=[('phd', 'Doctorado'), ('msc', 'Maestría'), ('dip', 'Diplomado'), ('curs', 'Cursos'), ('coleg', 'Colegio')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='programmember',
            name='institution',
            field=models.CharField(default='UH', max_length=100),
        ),
        migrations.CreateModel(
            name='StudentOthers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('graduate_date', models.DateField(null=True)),
                ('init_date', models.DateField(null=True)),
                ('country', models.CharField(default='Cuba', max_length=70)),
                ('picture', models.ImageField(null=True, upload_to=programs.models.student_directory_path)),
                ('gender', models.CharField(default='f', max_length=1)),
                ('birth_date', models.DateField(default=django.utils.timezone.now)),
                ('dni', models.CharField(default='12345678901', max_length=24)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormationMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.CharField(choices=[('Director', 'Director'), ('Metodólogo', 'Metodólogo'), ('Técnico', 'Técnico')], max_length=20)),
                ('grade', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('picture', models.ImageField(blank=True, help_text='Foto', null=True, upload_to=programs.models.postg_member_directory_path)),
                ('gender', models.CharField(choices=[('f', 'Femenino'), ('m', 'Masculino')], default='f', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CursStudentTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500, null=True)),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.investigationline')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.investigationproject')),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.cursstudent')),
            ],
        ),
        migrations.AddField(
            model_name='cursstudent',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.program'),
        ),
        migrations.AddField(
            model_name='cursstudent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ColegStudentTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500, null=True)),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.investigationline')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.investigationproject')),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.colegstudent')),
            ],
        ),
        migrations.AddField(
            model_name='colegstudent',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.program'),
        ),
        migrations.AddField(
            model_name='colegstudent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseevaluation',
            name='colegstudent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.colegstudent'),
        ),
        migrations.AddField(
            model_name='courseevaluation',
            name='cursstudent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.cursstudent'),
        ),
        migrations.AddField(
            model_name='message',
            name='coleg_student_receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.colegstudent'),
        ),
        migrations.AddField(
            model_name='message',
            name='curs_student_receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.cursstudent'),
        ),
        migrations.AddField(
            model_name='messagesended',
            name='coleg_student_receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.colegstudent'),
        ),
        migrations.AddField(
            model_name='messagesended',
            name='curs_student_receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.cursstudent'),
        ),
        migrations.AddField(
            model_name='studentfiledocument',
            name='coleg_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.colegstudent'),
        ),
        migrations.AddField(
            model_name='studentfiledocument',
            name='curs_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.cursstudent'),
        ),
        migrations.AddField(
            model_name='studentfinishrequirement',
            name='colecg_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.colegstudent'),
        ),
        migrations.AddField(
            model_name='studentfinishrequirement',
            name='curs_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.cursstudent'),
        ),
        migrations.AddField(
            model_name='studentinitrequirement',
            name='colecg_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.colegstudent'),
        ),
        migrations.AddField(
            model_name='studentinitrequirement',
            name='curs_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.cursstudent'),
        ),
        migrations.AddField(
            model_name='tuthor',
            name='coleg_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.colegstudent'),
        ),
        migrations.AddField(
            model_name='tuthor',
            name='curs_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.cursstudent'),
        ),
    ]
