# Generated by Django 4.2.1 on 2025-04-22 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0139_colegstudent_cursstudent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DipStudentTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500, null=True)),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.investigationline')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.investigationproject')),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.mscstudent')),
            ],
        ),
    ]
