# Generated by Django 4.2.1 on 2025-04-24 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0140_dipstudenttheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='formationmember',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.program'),
        ),
    ]
