# Generated by Django 4.2.1 on 2025-09-23 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0141_formationmember_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formationmember',
            name='program',
        ),
    ]
